language: python
python:
- '3.6'

dist: trusty


before_install:
  - sudo apt-get install xvfb
before_script:
  # google chrome standalone driver
  - wget https://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin
  - sudo chmod a+x /usr/bin/chromedriver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
- pip install -r requirements.txt
- python manage.py collectstatic --noinput

script: python manage.py test app


cache: pip

notifications:
  slack:
    secure: iGDu26rpYK6k4AGGh5YBilBOkvZEVBVNE6xH/pC8Y/1nDm14nRHkNIJ3JSlv4hDUKrhiYesIPja/u/ZX8sWlA+BW6BlykO0726HYQ5Ii/udh3OiZmNXBv/IDI45xfe6zf5bMxZzb+WhUVgcdN64Yr2z+qM3y9nmH2mc8yH/ci8u12mKB9i/NoDduvlfCqF74qfmMw5dHFTXsUKeazale3NvY2ZxZsil+D1lF6EZ3LaddBjkESxfFVdG8JgbD0zOD+B59Xxz21R/F9+2eWNiPOwayHt5D0hESiWyjFhQ0J0Ft1WhZ90jo/shkj0/05BKbMVFMEwsdLhTZXNy1LeMqA8y5LIyVM818GApxYsQ2HvGe1dKDWTxXD9k2n3/io8iRC8ZFBPdaZE1hQnKc3dDtkh1CP7ehxo2otFZA9TF0Oj7h081XeqBtjhSVxNVjhzuLwfVgFlXexm63i4xh5bRwkpppZdmjZD1vCPZHZnJyh4s1ESkcsiJ1PS4jyoMe81/zQ76qXdFi5eTCaApkP2t5CBjbFeUaCUus8MS+WyRScK340bF4KHzbkHgE3H+lAkI8O7LgK6Pe+QQLchz6UdwIA8S5/o7L1xLa/VMJ/RXnkLNsJHzX9Q391OhDcvJQi8WxCuZdMCgmA8sXSat/J6v551HRxh4Z0t18sR0p/6+yquw=
env:
  secure: NSdLJPs/L0a91lD0H470usbTR3DsEsmgfHAkDbpBD196mVkF5efdbsHLeO0FSiTkxRl2EYmJGeJHXWulmJfsQlrBPppuisvuxjVGfIPHVGxS30SuYrsbNJ/HoD2rdi1ZdvBu7FBTIeCSurhnv/y6qgJNc0QDaXiWKSiUC20w1V4lAUwQpfj0k/4b+zrSyoadDCg0xFFCPTHODAah5S8yvXxNih7HdnAGoN3mLEP7+1UvO1+zed85fMTk1B+Ae1qdy4eXr/xmvaSvvS9rVygWBuOUKCZ/MEb56yDFU0xTTgbLP9xMVte/tKdj3EeU+T4AvMJOucfLZ+VkTREvR/jLaLDGQh9hjzg6OhbDn445YidZVyqFDsGZ+j+pVfAIf4Z4PXv2GpvMUbeNRzroTBSBY0hhEyTUHPTLibCVuZb6+i8NxBihjlv0roXp4EjveYPwRRAna+FSdWPiVcA/pRs1hJSSsnfM105RG71tVAk2BtYjWXphIyL4r2Hii2gqhv3tWEWg2UOwJ4s9NjbKrSsptta+PEZpgl9b0HuS5rohYuelorPrsReBa4QFDlSQ149dJ8qJm57PhMqi+qPuwjC5RJ+78CK28qZBeI5BA6VziYfQAoT1+MY6fjiTq3H4B/sZ6g4QKLI4GO7KWrUuTMB5Vtwqg72cxgj2g+UVUNTObHY=
